
// import type { BusinessOutput } from '../../types';
// import { ShieldAlert, Lightbulb, CheckCircle2 } from "lucide-react";

// const BusinessSummary: React.FC<{ aiRawOutput: BusinessOutput }> = ({ aiRawOutput }) => {
//   return (
//     <div className="bg-white shadow-sm rounded-2xl p-8 space-y-10">
//       {/* Title */}
//       <h2 className="text-3xl font-bold text-gray-900 border-b pb-4">Business Contract Summary</h2>

//       {/* About */}
//       <p className="text-gray-700 leading-relaxed">{aiRawOutput.about}</p>

//       {/* Clauses */}
//       <div>
//         <h3 className="text-xl font-semibold text-gray-800 mb-4">📑 Clauses</h3>
//         <div className="space-y-6">
//           {aiRawOutput.clauses.map((clause, i) => (
//             <div key={i} className="border-l-4 border-blue-500 pl-4">
//               <h4 className="text-lg font-semibold text-gray-800">{clause.title}</h4>
//               <p className="text-gray-600 mb-3">{clause.explanation}</p>

//               <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
//                 <div className="flex items-start gap-2 bg-red-50 p-4 rounded-lg">
//                   <ShieldAlert className="text-red-600 w-6 h-6 mt-1" />
//                   <p className="text-sm leading-relaxed text-red-700">
//                     <b>Risk:</b> {clause.risk}
//                   </p>
//                 </div>
//                 <div className="flex items-start gap-2 bg-green-50 p-4 rounded-lg">
//                   <Lightbulb className="text-green-600 w-6 h-6 mt-1" />
//                   <p className="text-sm leading-relaxed text-green-700">
//                     <b>Improvement:</b> {clause.improvement}
//                   </p>
//                 </div>
//               </div>

//             </div>
//           ))}
//         </div>
//       </div>

//       {/* Financials */}
//       <div>
//         <h3 className="text-xl font-semibold text-gray-800 mb-4">💰 Financials</h3>
//         <p className="mb-2"><b>Total Fee:</b> {aiRawOutput.financials.totalFee}</p>

//         <div className="space-y-3 pl-3 border-l-2 border-gray-300">
//           {aiRawOutput.financials.paymentMilestones.map((m, i) => (
//             <div key={i} className="flex items-center gap-3">
//               <CheckCircle2 className="text-blue-600 w-5 h-5" />
//               <span className="text-gray-700">{m}</span>
//             </div>
//           ))}
//         </div>

//         <p className="mt-3"><b>Late Fee:</b> {aiRawOutput.financials.lateFee}</p>
//       </div>

//       {/* Compliance Notes */}
//       <div>
//         <h3 className="text-xl font-semibold text-gray-800 mb-3">📌 Compliance Notes</h3>
//         <div className="flex flex-wrap gap-2">
//           {aiRawOutput.keyComplianceNotes.map((c, i) => (
//             <span 
//               key={i} 
//               className="px-3 py-1 bg-gray-100 text-gray-700 text-sm rounded-full border"
//             >
//               {c}
//             </span>
//           ))}
//         </div>
//       </div>

//       {/* Final Assessment */}
//       <div className="p-6 rounded-xl bg-gray-50 border">
//         <h3 className="text-lg font-semibold text-gray-800 mb-2">Final Assessment</h3>
//         <p>
//           <span 
//             className={`px-3 py-1 rounded-full text-sm font-medium ${
//               aiRawOutput.finalAssessment.overallRisk === "High"
//                 ? "bg-red-100 text-red-700"
//                 : aiRawOutput.finalAssessment.overallRisk === "Medium"
//                 ? "bg-yellow-100 text-yellow-700"
//                 : "bg-green-100 text-green-700"
//             }`}
//           >
//             {aiRawOutput.finalAssessment.overallRisk}
//           </span>
//         </p>
//         <p className="text-gray-700 mt-2">{aiRawOutput.finalAssessment.comment}</p>
//       </div>

//       {/* Footer Branding (Web) */}
//       <footer className="pt-6 mt-8 border-t border-gray-200 text-center text-xs text-gray-500">
//         Generated by <span className="font-semibold">Know Your Terms</span>
//       </footer>
//     </div>
//   );
// };

// export default BusinessSummary;





import type { BusinessOutput as ImportedBusinessOutput, DeterministicRiskFinding } from '../../types';

// Type guard for new API shape
function isNewAssessment(obj: any): obj is { overallScore: number; recommendations: string[] } {
  return obj && typeof obj.overallScore === 'number' && Array.isArray(obj.recommendations);
}
import { ShieldAlert, Lightbulb, CheckCircle2 } from "lucide-react";

const renderBoldMarkdown = (text: string) => {
  return text
    .split(/(\*\*[^*]+\*\*|\*[^*\n]+\*)/g)
    .filter(Boolean)
    .map((part, index) => {
      const isDoubleAsteriskBold = part.startsWith("**") && part.endsWith("**");
      const isSingleAsteriskBold = part.startsWith("*") && part.endsWith("*");

      if (isDoubleAsteriskBold || isSingleAsteriskBold) {
        const trimLength = isDoubleAsteriskBold ? 2 : 1;
        return <strong key={`${part}-${index}`}>{part.slice(trimLength, -trimLength)}</strong>;
      }

      return <span key={`${part}-${index}`}>{part}</span>;
    });
};

const getSeverityBadgeClasses = (severity: DeterministicRiskFinding["severity"]) => {
  if (severity === "high") return "bg-red-100 text-red-700 border-red-200";
  if (severity === "medium") return "bg-amber-100 text-amber-700 border-amber-200";
  return "bg-emerald-100 text-emerald-700 border-emerald-200";
};

const CircularScore: React.FC<{ score: number }> = ({ score }) => {
  // Score is out of 10, convert to percent
  const percent = Math.round((score / 10) * 100);
  const radius = 40;
  const stroke = 7;
  const normalizedRadius = radius - stroke / 2;
  const circumference = normalizedRadius * 2 * Math.PI;
  const strokeDashoffset = circumference - (percent / 100) * circumference;
  return (
    <svg height={radius * 2} width={radius * 2} className="block mx-auto">
      <circle
        stroke="#e5e7eb"
        fill="none"
        strokeWidth={stroke}
        cx={radius}
        cy={radius}
        r={normalizedRadius}
      />
      <circle
        stroke="#2563eb"
        fill="none"
        strokeWidth={stroke}
        strokeLinecap="round"
        cx={radius}
        cy={radius}
        r={normalizedRadius}
        strokeDasharray={circumference}
        strokeDashoffset={strokeDashoffset}
        style={{ transition: 'stroke-dashoffset 0.5s' }}
      />
      <text
        x="50%"
        y="50%"
        textAnchor="middle"
        dy=".3em"
        fontSize="1.5rem"
        fill="#2563eb"
        fontWeight="bold"
      >
        {score}
      </text>
    </svg>
  );
};

const BusinessSummary: React.FC<{ aiRawOutput: ImportedBusinessOutput }> = ({ aiRawOutput }) => {
  const assessment = aiRawOutput.finalAssessment;
  const isNew = isNewAssessment(assessment);
  const deterministicFindings = Array.isArray(aiRawOutput.deterministicRiskFindings)
    ? aiRawOutput.deterministicRiskFindings
    : [];
  // Defensive: get title if present and is a string
  const summaryTitle = typeof (aiRawOutput as any).title === 'string' && (aiRawOutput as any).title
    ? (aiRawOutput as any).title
    : 'Business Contract Summary';
  return (
    <div className="relative">
      {/* Fixed Title */}
      <div className="sticky top-0 z-10 bg-white pb-2 border-b border-gray-200">
        <h2 className="text-3xl font-bold text-gray-900 px-8 pt-6 pb-4 w-full">{summaryTitle}</h2>
      </div>
      <div className="flex flex-col lg:flex-row items-start gap-6">
        {/* Left: Main Content */}
        <div className="w-full lg:w-3/4 lg:min-w-0">
          <div className="bg-white rounded-2xl p-8 space-y-10">
            {/* About */}
            <div>
              <h3 className="text-xl font-semibold text-gray-800 mb-2">About</h3>
              <p className="text-gray-700 leading-relaxed">{aiRawOutput.about}</p>
            </div>

            {/* Clauses */}
            <div>
              <h3 className="text-xl font-semibold text-gray-800 mb-4">📑 Clauses</h3>
              <div className="space-y-6">
                {aiRawOutput.clauses.map((clause, i) => (
                  <div key={i} className="border-l-4 border-blue-500 pl-4">
                    <h4 className="text-lg font-semibold text-gray-800">{clause.title}</h4>
                    <p className="text-gray-600 mb-3">{clause.explanation}</p>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                      <div className="flex items-start gap-2 bg-red-50 p-4 rounded-lg">
                        <ShieldAlert className="text-red-600 w-6 h-6 mt-1" />
                        <p className="text-sm leading-relaxed text-red-700">
                          <b>Risk:</b> {clause.risk}
                        </p>
                      </div>
                      <div className="flex items-start gap-2 bg-green-50 p-4 rounded-lg">
                        <Lightbulb className="text-green-600 w-6 h-6 mt-1" />
                        <p className="text-sm leading-relaxed text-green-700">
                          <b>Improvement:</b> {clause.improvement}
                        </p>
                      </div>
                    </div>

                    {Array.isArray(clause.citations) && clause.citations.length > 0 && (
                      <div className="mt-3 rounded-lg border border-slate-200 bg-slate-50 p-3">
                        <p className="text-xs font-semibold uppercase tracking-wide text-slate-600 mb-2">
                          Evidence from Agreement
                        </p>
                        <ul className="space-y-2">
                          {clause.citations.map((citation, citationIndex) => (
                            <li key={`${citation.location}-${citationIndex}`} className="text-sm text-slate-700 leading-relaxed">
                              <p className="text-xs text-slate-500 mb-1">{citation.location}</p>
                              <p>"{citation.quote}"</p>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                  </div>
                ))}
              </div>
            </div>

            {/* Financials */}
            <div>
              <h3 className="text-xl font-semibold text-gray-800 mb-4">💰 Financials</h3>
              <p className="mb-2"><b>Total Fee:</b> {aiRawOutput.financials.totalFee}</p>

              <div className="space-y-3 pl-3 border-l-2 border-gray-300">
                {aiRawOutput.financials.paymentMilestones.map((m, i) => (
                  <div key={i} className="flex items-center gap-3">
                    <CheckCircle2 className="text-blue-600 w-5 h-5" />
                    <span className="text-gray-700">{m}</span>
                  </div>
                ))}
              </div>

              <p className="mt-3"><b>Late Fee:</b> {aiRawOutput.financials.lateFee}</p>
            </div>

            {/* Compliance Notes */}
            <div>
              <h3 className="text-xl font-semibold text-gray-800 mb-3">📌 Compliance Notes</h3>
              <div className="flex flex-wrap gap-2">
                {aiRawOutput.keyComplianceNotes.map((c, i) => (
                  <span 
                    key={i} 
                    className="px-3 py-1 bg-gray-100 text-gray-700 text-sm rounded-full border"
                  >
                    {c}
                  </span>
                ))}
              </div>
            </div>

            {/* Final Assessment */}
            <div className="p-6 rounded-xl bg-gray-50 border">
              <h3 className="text-lg font-semibold text-gray-800 mb-2">Final Assessment</h3>
              <p className="text-gray-700 mt-2">
                {assessment && assessment.comment
                  ? assessment.comment
                  : <span className="text-gray-400">No assessment comment available</span>
                }
              </p>
            </div>

            {deterministicFindings.length > 0 && (
              <div>
                <h3 className="text-xl font-semibold text-gray-800 mb-4">Deterministic Risk Checks</h3>
                <div className="space-y-4">
                  {deterministicFindings.map((finding) => (
                    <div key={finding.ruleId} className="rounded-xl border border-gray-200 p-4 bg-white shadow-sm">
                      <div className="flex flex-wrap items-center gap-2 mb-2">
                        <p className="text-base font-semibold text-gray-800">{finding.title}</p>
                        <span className={`text-xs font-semibold uppercase px-2 py-1 rounded-full border ${getSeverityBadgeClasses(finding.severity)}`}>
                          {finding.severity}
                        </span>
                      </div>
                      <p className="text-sm text-gray-700 mb-2">{finding.issue}</p>
                      <p className="text-sm text-blue-700 mb-3">
                        <strong>Recommendation:</strong> {finding.recommendation}
                      </p>
                      <ul className="space-y-2">
                        {finding.citations.map((citation, index) => (
                          <li key={`${finding.ruleId}-${citation.location}-${index}`} className="text-sm text-slate-700">
                            <p className="text-xs text-slate-500 mb-1">{citation.location}</p>
                            <p>"{citation.quote}"</p>
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Right: Score & Recommendations */}
        <div className="w-full lg:w-1/4 lg:min-w-[280px] flex-shrink-0">
          <div className="bg-white shadow rounded-2xl py-6 px-4 flex flex-col items-center sticky top-28">
            <h3 className="text-lg font-semibold text-gray-800 mb-4">Overall Score</h3>
            {isNew ? (
              <CircularScore score={assessment.overallScore} />
            ) : (
              <div className="text-gray-400 text-sm mb-4">No score available</div>
            )}
            <div className="mt-6 w-full">
              <h4 className="text-base font-semibold text-gray-800 mb-2">Recommendations</h4>
              <ul className="list-disc pl-5 text-gray-700 text-sm space-y-2">
                {isNew && assessment.recommendations.length > 0
                  ? assessment.recommendations.map((rec: string, i: number) => (
                      <li key={i} className="leading-relaxed">
                        {renderBoldMarkdown(rec)}
                      </li>
                    ))
                  : <li className="text-gray-400">No recommendations available</li>
                }
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BusinessSummary;

